version: '3.7'

# docker volume create --name data -d local

services:
  db:
    restart: always
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    #tty: true
    volumes:
       - data:/var/lib/postgresql/data
volumes:
  data:
    external: true