version: '3.7'

# docker volume create --name data -d local

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  db:
    restart: always
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    #tty: true
    volumes:
       - data:/var/lib/postgresql/data
volumes:
  data:
    external: true