version: '2'

# docker volume create --name data -d local

services:
  db:
    restart: always
    image: postgres
    container_name: postgres_db
    #tty: true
    volumes:
       - data:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    tty: true
    stdin_open: true
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  data:
    external: true