version: '3.7'

# docker volume create --name data -d local

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    container_name: backend
    build:
      context: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - 3100:3100
  db:
    restart: always
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    volumes:
      - data:/var/lib/postgresql/data
  db_ui:
    restart: always
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: pass
volumes:
  data:
    external: true