source 'https://rubygems.org'

gem 'hashie', '~> 4.1.0'
gem 'inflecto', '~> 0.0.2'

gem 'oj'
# gem 'haml'
gem 'roda', '~> 3.44.0'

# docker tmp server (nginx + passenger is ideal)
gem 'puma', '~> 5.3.2'

gem 'rack-unreloader', '~> 1.7.0'