default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: pass
  pool: 5

development:
  <<: *default
  database: myapp_development


test:
  <<: *default
  host: <%= ENV['TRAVIS'] ? 'localhost' : 'db' %>
  database: myapp_test

production:
  <<: *default
  database: GameTracker_production
  username: GameTracker
  password: <%= ENV['GAMETRACKER_DATABASE_PASSWORD'] %>